### PR TITLE
when week / month view. highlight current period on mini calendar

### PR DESCRIPTION
**Pull request by jasper2virtual**

### CODE REVIEW

**Comment by jasper2virtual** [comment]
- week view  

image

- month view  

image

**Comment by campbell-m** [comment]
Thanks.  This looks good.  However before it can be merged it needs to take account of the MRBS config setting `$weekstarts`.

**Review by campbell-m — COMMENTED** [review]
Can you separate out different issues into different pull requests please?  And for this issue can you describe in more detail how to reproduce it?  And using which browser?

**Comment by jasper2virtual** [comment]
> Can you separate out different issues into different pull requests please?  And for this issue can you describe in more detail how to reproduce it?  And using which browser?

Sorry, I also intended to submit it in another issue. 
Sorry I don't know why GitHub auto merge it.
I scratch my head for hours yesterday. 
I will try to fix it again today.

Would you wait for me to fix it. Sorry about that. I try again today

**Comment by jasper2virtual** [comment]
I think I re-create the pull request later. sorry about it.

**Comment by jasper2virtual** [comment]
> Thanks. This looks good. However before it can be merged it needs to take account of the MRBS config setting `$weekstarts`.

Thanks, I will test it again. and create a new pull request later. thanks for your reading.

**Comment by pa-jberanek** [comment]
If you want to develop more than one change simultaneously I believe you need branches in your fork of the project.

**Comment by jasper2virtual** [comment]
> If you want to develop more than one change simultaneously I believe you need branches in your fork of the project.
oh i see, sorry to make inconvenient, I am new to make pull request.
and sorry my english is bad. 
I will create another branch for each change and pull request later. thanks.

**Pull request closed without merging**
