### PR TITLE
Issue 3496

### PR DESCRIPTION
**Pull request by campbell-m**
Fix for Issue #3496

### CODE REVIEW

**Comment by William-Haller** [comment]
This isn't highlighting the last day of the week, last day of the month, and highlights the day before the date in date mode. I restarted the memcached, fpm and apache on both servers to try to make sure the proper code was being served. Unless I just really missed something in doing the change on my end this switches to the opposite problem (UTC) being a day ahead of us at times. Could be changing to a noon vs midnight as I did in my change helped as well, but this doesn't seem to be a solution.

**Comment by campbell-m** [comment]
What do you have `$weekstarts` set to?

**Comment by campbell-m** [comment]
Could you post a screenshot of what you are seeing please?

**Comment by campbell-m** [comment]
Also, could you post your copy of datepickr.js.php that you are using please?

**Comment by campbell-m** [comment]
@William-Haller - just wondering if you've had a chance to look at my comments?

**Comment by campbell-m** [comment]
Thanks.  I'm interested in the timezone that you see when you edit the area in question.  Login to MRBS as an admin, go to the Rooms page, select the area in question and click the Edit icon (little pencil).  The config setting for timezone just sets the default timezone for new areas.  I want to check that your area is actually on MDT and not some other timezone.  Although you are seeing MDT in the JavaScript console, that timezone is determined by your browser or PC and not by MRBS.

**Comment by William-Haller** [comment]
The timezone appears as Denver in that display, which would be correct.

**Comment by campbell-m** [comment]
OK, thanks.  Could you post a screenshot please of the problem you are seeing?  Unfortunately I am unable to reproduce the problem, despite changing the timezone in my browser.  The PR does fix a problem, but obviously not the problem you are seeing.

**Comment by William-Haller** [comment]
Screenshot_20230911_075638
Screenshot_20230911_075522
Screenshot_20230911_075609

No highlighted date in day view although correct day is circled. All other displays are off by one.

**Comment by campbell-m** [comment]
Thanks.  And could you also post the copy of datepickr.js.php that you are using please?  Just to double-check that you are using the correct version.

**Comment by William-Haller** [comment]
[datepicker.zip](https://github.com/meeting-room-booking-system/mrbs-code/files/12577164/datepicker.zip)
datepicker.js.php is what is running now. o_ is my mods converting the date to noon vs. midnight and adjusting by time zone. n_datepicker.js.php is what produced the console logs in the earlier post. No difference in displays posted between datepicker.js.php and n_datepicker.js.php. o_datepicker.js.php displays the proper highlighted dates.

**Comment by campbell-m** [comment]
Thanks.  I can now reproduce the problem.  I had to change my PC's timezone.  It seems that changing the sensors in Chrome's development tools wasn't enough.

**Comment by campbell-m** [comment]
OK, I can see the problem.  Fix coming up later.

**Comment by campbell-m** [comment]
I've now committed a further fix in [349ee9c](https://github.com/meeting-room-booking-system/mrbs-code/pull/3498/commits/349ee9c91e02711fcea5db293e8cd8564c407073).  I had fallen foul of this quirk:

"When the time zone offset is absent, date-only forms are interpreted as a UTC time and date-time forms are interpreted as local time. This is due to a historical spec error that was not consistent with ISO 8601 but could not be changed due to web compatibility."

Could you test the latest datepickr.js.php code please?

**Pull request merged**
