### PR TITLE
att

### PR DESCRIPTION
**Pull request by MayconPadilha**

### CODE REVIEW

**Comment by campbell-m** [comment]
I know this has been closed, but just looking at your changes you shouldn't be making changes to areadefaults.inc.php and systemdefaults.inc.php.  Instead put any changes in config.inc.php which overrides those two files.  That way any changes will survive an upgrade to a new release of MRBS.

Similarly, do not change mrbs.css.php but instead create a custom CSS file (see systemdefaults.inc.php for how to do this).

**Comment by MayconPadilha** [comment]
Sorry for creating this pull request, it was by accident, I don't speak English very well, I'm using Google Translate.

I have a question about config.inc.php, I tried to use it as recommended above, but I couldn't, it didn't replace the configuration files in the areadefaults.inc.php and systemdefaults.inc.php files, what else should I do to make it work?

I have another question about the timezone, I tried using $timezone = "America/Sao_Paulo";
I tried using it in all three files and it didn't work.

**Comment by campbell-m** [comment]
> I have another question about the timezone, I tried using $timezone = "America/Sao_Paulo";
I tried using it in all three files and it didn't work.

The timezone in the configuration file just sets the default timezone. If you have already created areas you will need to edit the settings for each area.  Log in to MRBS as an admin, go to the Rooms page, select the area in question and click the Edit icon (little pencil).  Make the changes and click Save.

> I have a question about config.inc.php, I tried to use it as recommended above, but I couldn't, it didn't replace the configuration files in the areadefaults.inc.php and systemdefaults.inc.php files, what else should I do to make it work?

This may be the same problem - the settings you are are trying to change may have to be edited in the area settings page.

**Comment by campbell-m** [comment]
It may be because you are using Docker.  I am not familiar with Docker so don't know how it works.  But I see in the source distribution that there is another config file:  docker_app/php/config.inc.php.

**Pull request closed without merging**
