### PR TITLE
import enhacements for google calender ical

### PR DESCRIPTION
**Pull request by being-peace**
Additional features:

- import from url, e.g. google calender ical
- make parsing of area/room optional
- optional delete room before import
- option to skip past

Fixes:

- defensive programming for incomplete timedate syntax

Incomplete / Issues:

- There are dependencies that are not depicted in the web form. I don´t know how to do it in an easy manner. If the URL is given, the download does not make sense. Only if the parsing is enabled, the parsing inputs make no sense. If parsing is enabled, the deletion of all bookings is not appropriate.
- I don´t know if the deletion should be allowed. In my use case, we will regularly import from a google calender.
- There is no checking for the correct syntax of the url and retrieval errors. 
- I don´t know how to deal with all the languages files correctly.

If you are interested in the features, but need some changes, feel free to request them or fix them yourself.

### CODE REVIEW

**Comment by campbell-m** [comment]
Thanks for the ideas.  I've now taken them and pushed some code into the main branch.  I've done things slightly differently as you'll see so that the URL can be validated and the URL and file fields can be toggled.

I have yet done anything on area_room_parsing.  I'm not sure what your goal there was?

I don't think there should be an option to delete existing bookings. I think that should be something that is done separately by the admin beforehand.

**Comment by being-peace** [comment]
> I have yet done anything on area_room_parsing. I'm not sure what your goal there was?

When you want to import bookings that have been in a google calender before, it currently does not work, because LOCATION entries are parsed for a area/room and any entry with some LOCATION is rejected. Only for empty LOCATION the "default room" is used. 
With area_room_parsing=FALSE the whole parsing is deactivated and everything goes into the "default room" defined on the import. I think, this is quite useful. Sorry, if the wording and comments were not appropriate.

> I don't think there should be an option to delete existing bookings. I think that should be something that is done separately by the admin beforehand.

I admit that my use case is probably to special here: My goal was to regularly import bookings from a google calendar. They basically only displayed in MRBS. 
Yet, I can imagine that this option may be useful in other contexts, too. When you do a first time import, you may wish to do it repeatedly to adjust data. But it can´t be done, because existing entries block new imports. (The meaning of "Skip" is a little strange here).

**Comment by campbell-m** [comment]
> With area_room_parsing=FALSE the whole parsing is deactivated and everything goes into the "default room" defined on the import. I think, this is quite useful. Sorry, if the wording and comments were not appropriate

Ah, I understand.  Maybe something like "Ignore LOCATION data and use the default room".  I'll add it in.

> Yet, I can imagine that this option may be useful in other contexts, too. When you do a first time import, you may wish to do it repeatedly to adjust data. But it can´t be done, because existing entries block new imports. (The meaning of "Skip" is a little strange here).

Let me have a think about it.  One thought I had is that a Test box might be useful, which lets you run an import without altering the database.

**Comment by being-peace** [comment]
Thanks, in fact I used the LOCATION information as an addition in the description field. I will have a look, how you implemented things. 

Regarding the deletion: What are the use cases for import? You will have data in a different source of information you want to import. If there are no entries for your current room then deletion or not does not make a difference. If there are entries in your current room than there are good reasons to delete them, because otherwise you cannot be sure, that they will be imported, in case of conflicts.

**Comment by campbell-m** [comment]
> Thanks, in fact I used the LOCATION information as an addition in the description field. I will have a look, how you implemented things.

Yes, I saw that, but chose not to add the LOCATION information to the description.  While it may be useful in your scenario I think that in the general case the DESCRIPTION field should not be altered.

> Regarding the deletion: What are the use cases for import? You will have data in a different source of information you want to import. If there are no entries for your current room then deletion or not does not make a difference. If there are entries in your current room than there are good reasons to delete them, because otherwise you cannot be sure, that they will be imported, in case of conflicts.

I think there are a number of options and I'm not sure yet which would be best:

1. Have a Test import feature which allows you the run the import without writing to the database so that you can see where the conflicts are.
2. Delete any conflicting bookings.
3. Overwrite any conflicting bookings (ie just delete the part of the booking that you need to)
4. Delete all bookings in a room
5. Delete all future bookings in a room if import_past is not set.

I'm inclined towards (1) at the moment as it's the least severe, but would be interested in understanding your use case.   Up until now I had imagined that Import would only be used when migrating from one booking system to another, but you seem to be doing regular imports and it would be good to understand that a bit more.

**Comment by being-peace** [comment]
Keep in mind, that MRBS is designed as a room booking system, but it can be useful for any kind of resource booking. And then, while importing, the LOCATION information might be interesting. But again, go ahead, I will merge your implementation with my changes and we can enjoy the beauty of open source and github. :-)

You really want to understand the use case for the frequent imports? Okay, here you are! :-) 
Yes, importing should be typically used for migration. In our case we have two booking systems that will for institutional reasons continue to be used in parallel, but there is one ressource that needs to be shown in both calenders (it is acceptable, if it is edited only in one). One is MRBS and one is based on a google calendar (which is then embedded in other calendars...). So we needed some kind of sync. First I exported MRBS to the google calender, by making the google calender read from a ICS file, which was frequently updated. Unfortunately, I learned that google refreshes calenders only every infrequent and the method was not acceptable.
So, we now try the syncing the other way around. Frequent import of the google calender (via URL), replacing everything that has been there before.
It´s Always the Goddamned Interfaces https://www.oreilly.com/library/view/adrenaline-junkies-and/9780133492286/ch43.html

I guess this is not a use case, you need to take care for. :-)

**Comment by campbell-m** [comment]
OK, thanks, I understand.

As you'll probably have seen I've now pushed an "ignore location" option to the main branch.

**Comment by campbell-m** [comment]
> And then, while importing, the LOCATION information might be interesting

I have pushed a change to the main branch which allows you optionally to add the LOCATION to the description.  The format of the output is determined by a vocab tag, so you can override it.

**Pull request closed without merging**
