### PR TITLE
Edit entry handler back button

### PR DESCRIPTION
**Pull request by jberanek**
Just turning this branch into a PR, for visibility/discussion. See #6

### CODE REVIEW

**Comment by being-peace** [comment]
1. Great that you turned the branch into a separate PR. The discussion in https://github.com/meeting-room-booking-system/mrbs-code/pull/6 was in a wrong place and I was always searching where to find it.
2. Regarding the two bugs in https://github.com/meeting-room-booking-system/mrbs-code/pull/6#issuecomment-898369573: a) is fixed, the conflicting times are displayed, yet b) is still there. Browser: firefox, Chrome both on Windows

**Comment by campbell-m** [comment]
I'm struggling to reproduce this problem on periods.   Could you give exact steps to reproduce it please?

**Comment by being-peace** [comment]
You have seen the video?

1. I have a Area with a room with two periods.
2. I add a booking for the current day for the second period.
3. I edit an additional booking for the current day with the first and the second period.
4. I submit
5. I click "back".

Expected: Period fields as before
Seen: Period field are read only (in Firefox & Chrome).

Does this help?

Sorry, for so much hassle. Are you still convinced that it is a robust solution for diverse settings? Do you have a possibility to check for additional fields with different types?

**Comment by campbell-m** [comment]
OK, I understand what is happening now.  The system is behaving correctly.  What is happening is that in your periods example you have selected all the periods in the day.   So when you return to the form the periods are greyed out because the "All day" checkbox is checked.  If you uncheck that checkbox you will find that the periods are un-greyed.   This is the same behaviour as when you create a booking that uses all the periods in a day and then later edit the booking.

Yes, I am convinced it is a robust solution.  It is much simpler than the alternative of checking the GET or POST data.  This solution does not need to know about MRBS fields.  All it needs to know about is how to handle the various different types of form element, eg checkboxes, radio buttons, select elements etc.

**Comment by being-peace** [comment]
Oh, sorry, I did not notice that. It´s clearly to see in the video. :-)
Thank you for your patience.

**Pull request merged**
