### PR TITLE
Adding all locales to Docker

### PR DESCRIPTION
**Pull request by ma-wenqian**
Fixed 'Server failed to set locale to' error by adding all locales.

### CODE REVIEW

**Comment by ma-wenqian** [comment]
https://github.com/meeting-room-booking-system/mrbs-code/issues/3615
https://github.com/meeting-room-booking-system/mrbs-code/issues/80
https://github.com/meeting-room-booking-system/mrbs-code/issues/3642

**Comment by jberanek** [comment]
How much bigger does this make the container image?

**Comment by jberanek** [comment]
Also a minor nit-pick, I'd prefer if the PR didn't remove the final linefeed from the changed files.

**Comment by ma-wenqian** [comment]
After installing all locales, the image becomes around 200MB bigger.

**Review by jberanek — APPROVED** [review]
Looks good to me.

**Pull request merged**
