### PR TITLE
Use browser history´s back on edit_event_handler.php

### PR DESCRIPTION
**Pull request by being-peace**
See https://github.com/meeting-room-booking-system/mrbs-code/issues/5

Even better UI would be, if it is not possible to submit an entry with a conflict (if it´s not a repeated one with the checkbox for "ignore conflicts" is on).

### CODE REVIEW

**Comment by campbell-m** [comment]
Thanks for pointing this out.  I agree that it would be better to return to the edit_entry page with all the fields filled in.   However, unless I'm missing something I don't think window.history.back() will do this?   It doesn't retain the POST data as far as I'm aware?  (One other problem: the PR code didn't seem to  work at all for me - it failed on a CSRF token check - not quite sure why, but if you don't get the POST data it doesn't really matter.)

I think I'll work on a fix that goes back to the edit_entry page with all the form data preserved.

**Comment by campbell-m** [comment]
I've now implemented in the [edit_entry_handler_back_button branch](https://github.com/meeting-room-booking-system/mrbs-code/tree/edit_entry_handler_back_buttonl) repopulation of the original form after pressing the Back button on the edit_entry_handler page.  Let me know if this does what you expect before I merge it back into the main branch.

**Comment by being-peace** [comment]
Thanks for your work and sorry for the delay.

1. The history.back() has no CSRF issue, because the page is created again, with blank fields as it would with clicking from the index.php. Yet, it is definitely not optimal.
2. The implementation in https://github.com/meeting-room-booking-system/mrbs-code/tree/edit_entry_handler_back_button **does not** work for me. I tried with an area with series and a second area. It seems that times and the selected ressource (aka room) is not repopulated.
3. Did I get it I right that you use the session.storage to preserve the values? I have doubts if this is the appropriate way to do it . Think of a situation where there are two entry_handler.php pages open. If a user hit´s back on the one entry after having commited the second entry, this will give very confusing results, won´t it? Wouldn´t it be better, to hand over all form attributes from the edit_entry_handler.php back to the edit_entry.php using the GET/PUT parameters that already exist? (edit_entry.php?view=day&year=2021&month=8&day=9&area=1&room=1...). This could be a much simpler and cleaner solution.
4. In my view, an even better UI would be, that it is not possible to submit an entry with a conflict (if it´s not a repeated one with the checkbox for "ignore conflicts" is on). What do you think?

**Comment by campbell-m** [comment]
> I tried with an area with series and a second area. It seems that times and the selected ressource (aka room) is not repopulated.

Can you give more detailed steps as to how to reproduce this please?  Also, what do you mean by a "second area" and what browser are you using?

> Did I get it I right that you use the session.storage to preserve the values?

Yes, it uses sessionStorage. 

> Think of a situation where there are two entry_handler.php pages open. If a user hit´s back on the one entry after having commited the second entry, this will give very confusing results, won´t it?

I don't think so: sessionStorage is specific to a tab as far as I understand.    Can you demonstrate this problem?

> Wouldn´t it be better, to hand over all form attributes from the edit_entry_handler.php back to the edit_entry.php using the GET/PUT parameters that already exist? (edit_entry.php?view=day&year=2021&month=8&day=9&area=1&room=1...). This could be a much simpler and cleaner solution.

Using GET would result in very long URLs, especially if there are a lot of custom fields.  I tried using POST, but it was pretty complicated and it turned out that sessionStorage seemed to be the cleanest solution.

> In my view, an even better UI would be, that it is not possible to submit an entry with a conflict (if it´s not a repeated one with the checkbox for "ignore conflicts" is on). What do you think?

It's obviously subjective, but I don't think so.  The user needs to be given some kind of explanation as to why they can't make a booking.  The red cross will give some feedback, but many users miss these and also it's not as easy to get the feedback on a small device (eg smart phone).  Going to a separate page that gives a clear explanation seems reasonable.

**Comment by being-peace** [comment]
> > I tried with an area with series and a second area. It seems that times and the selected ressource (aka room) is not repopulated.
> 
> Can you give more detailed steps as to how to reproduce this please? Also, what do you mean by a "second area" and what browser are you using?

I have a Period Area "P" and a Time Area "T". "P" is the first. I enter Area "T", create a conflict, come back, and the times are gone, and the rooms show the rooms of "P", but the Area is "T" and no room is selected. 

See attachments:
grafik
grafik

> 
> > Did I get it I right that you use the session.storage to preserve the values?
> 
> Yes, it uses sessionStorage.
> 
> > Think of a situation where there are two entry_handler.php pages open. If a user hit´s back on the one entry after having commited the second entry, this will give very confusing results, won´t it?
> 
> I don't think so: sessionStorage is specific to a tab as far as I understand. Can you demonstrate this problem?

You are right. I was wrong. :-)
> 
> > Wouldn´t it be better, to hand over all form attributes from the edit_entry_handler.php back to the edit_entry.php using the GET/PUT parameters that already exist? (edit_entry.php?view=day&year=2021&month=8&day=9&area=1&room=1...). This could be a much simpler and cleaner solution.
> 
> Using GET would result in very long URLs, especially if there are a lot of custom fields. I tried using POST, but it was pretty complicated and it turned out that sessionStorage seemed to be the cleanest solution.

To my feeling, a very long URL is not really a problem, and if it leads to more simple and robust implementation, it may be advantageous.
> 
> > In my view, an even better UI would be, that it is not possible to submit an entry with a conflict (if it´s not a repeated one with the checkbox for "ignore conflicts" is on). What do you think?
> 
> It's obviously subjective, but I don't think so. The user needs to be given some kind of explanation as to why they can't make a booking. The red cross will give some feedback, but many users miss these and also it's not as easy to get the feedback on a small device (eg smart phone). Going to a separate page that gives a clear explanation seems reasonable.

The small red cross at the very button is another UX issue, in my point of view. :-) The AJAX conflict detection is such a cool feature, but it is not very prominent.
And regarding the feedback: The verification gives already beautiful error messages, e.g. if an required field is not filled out. The same could be used for the conflicts.

**Comment by campbell-m** [comment]
> I have a Period Area "P" and a Time Area "T". "P" is the first. I enter Area "T", create a conflict, come back, and the times are gone, and the rooms show the rooms of "P", but the Area is "T" and no room is selected.

I have now pushed some changes to the branch which should fix this.  Could you test and confirm this please?

> To my feeling, a very long URL is not really a problem, and if it leads to more simple and robust implementation, it may be advantageous.

The main problem was not the long URL, though I think it's slightly undesirable to have very long URLs.   It was that using either GET or POST, the code to retrieve the form values in edit_entry.php was a bit long and complicated.  It turned out to be much simpler to do it in JavaScript using sessionStorage.

> And regarding the feedback: The verification gives already beautiful error messages, e.g. if an required field is not filled out. The same could be used for the conflicts.

I think that's a separate issue.  Even if there is client-side validation of the form in JavaScript, there will still need to be some server-side validation in case JavaScript is disabled or the user alters the page source.   Adding client-side validation can always be done later as a separate enhancement.

**Comment by being-peace** [comment]
Better, but still bugs:
a) With times, the times are not filled with the previous values
b) On periods, going back leave the from and to read-only

See atttached file.

https://user-images.githubusercontent.com/58709258/129346095-1e74c97d-a4d0-49ef-8ef5-d564934e63ef.mp4

**Comment by campbell-m** [comment]
Which browser are you using?

**Comment by campbell-m** [comment]
It's OK - I've worked it out (Firefox) and I can reproduce the problem on any browser.

**Comment by campbell-m** [comment]
I've now pushed a change to the branch which should fix that problem.  Could you retest please?

**Comment by campbell-m** [comment]
Superseded by https://github.com/meeting-room-booking-system/mrbs-code/pull/12

**Pull request closed without merging**
